# Generated by Django 4.2.5 on 2025-11-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverConduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('punctuality_score', models.FloatField(default=0)),
                ('route_adherence_score', models.FloatField(default=0)),
                ('stop_behavior_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.trucklocation')),
            ],
        ),
    ]
