# Generated by Django 4.2.5 on 2025-11-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_driverconduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=50)),
                ('scheduled_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('delay_minutes', models.FloatField(default=0.0)),
                ('predicted_status', models.CharField(blank=True, max_length=30, null=True)),
                ('confidence', models.FloatField(default=0.0)),
            ],
        ),
    ]
