# Generated by Django 4.2.5 on 2025-11-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_disposalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=100)),
                ('sectors', models.JSONField()),
                ('optimized_route', models.JSONField(blank=True, null=True)),
                ('time_saved', models.FloatField(default=0.0)),
                ('efficiency_gain', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
